name: Checkov Compliance Scan

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

  workflow_dispatch:

env:
  TF_WORKING_DIR: ./terraform

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install Checkov
      #   run: pip install checkov

      # - name: Run Checkov Scan
      #   run: checkov -d ./terraform --output-file-path checkov_results.json
      #   continue-on-error: true

      # - name: Upload Checkov Results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: checkov-results
      #     path: checkov_results.json











      - name: Checkov GitHub Action
        # You may pin to the exact commit or the version.
        # uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          # directory with infrastructure code to scan
          directory: ${{ env.TF_WORKING_DIR }}
          # Run scan only on a specific check identifier (comma separated)
          ## check: # optional
          # Run scan on all checks but a specific check identifier (comma separated)
          ## skip_check: # optional
          # display only failed checks
          ## quiet: # optional
          # Environment variable name of the Bridgecrew API key from Bridgecrew app
          ## api-key: # optional
          # do not return an error code if there are failed checks
          soft_fail: true # optional
          # run only on a specific infrastructure
          ## framework: # optional
          # comma separated list of external (custom) checks directories
          ## external_checks_dirs: # optional
          # comma separated list of external (custom) checks repositories
          ## external_checks_repos: # optional
          # The format of the output. cli, json, junitxml, github_failed_only, or sarif
          output_format: serif #optional, default is sarif
          # download external terraform modules from public git repositories and terraform registry:true, false
          ## download_external_modules: # optional
          # log level
          ## log_level: # optional, default is WARNING
          # checkov configuration file
          ## config_file: # optional
          # Path to a .checkov.baseline file to compare. Report will include only failed checks that are not in the baseline
          ## baseline: # optional
          # Do not return an error code only for specific check identifiers (comma separated)
          ## soft_fail_on: # optional
          # Return an error code only for specific check identifiers (comma separated)
          ## hard_fail_on: # optional
          # Set the username or UID used and optionally the groupname or GID for the action to run under
          ## container_user: # optional, default is 0
          




























# name: checkov

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   # push:
#   #   branches: [ "main", "master" ]
#   # pull_request:
#   #   branches: [ "main", "master" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "scan"
#   scan:
#     permissions:
#       contents: read # for actions/checkout to fetch code
#       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
#       actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
#       - uses: actions/checkout@v4

#       - name: Checkov GitHub Action
#         uses: bridgecrewio/checkov-action@v12
#         with:
#           # This will add both a CLI output to the console and create a results.sarif file
#           output_format: cli,sarif
#           output_file_path: console,results.sarif
        
#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v3
        
#         # Results are generated only on a success or failure
#         # this is required since GitHub by default won't run the next step
#         # when the previous one has failed. Security checks that do not pass will 'fail'.
#         # An alternative is to add `continue-on-error: true` to the previous step
#         # Or 'soft_fail: true' to checkov.
#         if: success() || failure()
#         with:
#           sarif_file: results.sarif