name: 'Terraform Plan/Apply'

on:
  #push:
    #branches:
    #- main
  #pull_request:
    #branches:
    #- main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Trigger Terraform destroy'
        required: false
        default: 'false'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  TF_WORKING_DIR: ./terraform

jobs:
  docs: 
    # name: 'Terraform Doc'
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v4
    #   with:
    #     token: ${{ secrets.TERRAFORM_DOCS_PAT_TOKEN }}
    #     ref: ${{ github.event.pull_request.head.ref }}
    # - name: Generate TF Docs
    #   uses: terraform-docs/gh-actions@v1.0.0
    #   with:
    #     find-dir: /
    #     git-push: true

    name: 'Terraform-Docs'
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: ${{ env.TF_WORKING_DIR }}
        output-file: TERRAFORM-DOCS.md # optional, default is README.md
        output-method: print


        #     # Name of terraform-docs config file. To enable, provide the file name (e.g. `.terraform-docs.yml`)
    #     config-file: # optional, default is disabled
    #     # Comma separated list of directories to generate docs for (ignored if `atlantis-file` or `find-dir` is set)
    #      working-dir: # optional, default is .
    #     # Name of Atlantis file to extract list of directories by parsing it. To enable, provide the file name (e.g. `atlantis.yaml`)
    #     atlantis-file: # optional, default is disabled
    #     # Name of root directory to extract list of directories by running `find ./find_dir -name *.tf` (ignored if `atlantis-file` is set)
    #     find-dir: # optional, default is disabled
    #     # If true it will update submodules recursively
    #     recursive: # optional, default is false
    #     # Submodules path to recursively update
    #     recursive-path: # optional, default is modules
    #     # terraform-docs format to generate content (see [all formats](https://github.com/terraform-docs/terraform-docs/blob/master/docs/FORMATS_GUIDE.md)) (ignored if `config-file` is set)
    #     output-format: # optional, default is markdown table
    #     # Method should be one of `replace`, `inject`, or `print`. Set as an empty string if `output.mode` and `output.file` are defined in config-file
    #     output-method: # optional, default is inject
    #     # File in module directory where the docs should be placed
        #     # When provided will be used as the template if/when the `output-file` does not exist. Set as an empty string if `output.template` is defined in config-file
    #     template: # optional, default is <!-- BEGIN_TF_DOCS -->
    # {{ .Content }}
    # <!-- END_TF_DOCS -->
    #     # Additional arguments to pass to the command (see [full documentation](https://github.com/terraform-docs/terraform-docs/tree/master/docs))
    #     args: # optional, default is 
    #     # Indention level of Markdown sections [1, 2, 3, 4, 5]
    #     indention: # optional, default is 2
    #     # If true it will commit and push the changes
    #     git-push: # optional, default is false
    #     # If empty the name of the GitHub Actions bot will be used (i.e. `github-actions[bot]`)
    #     git-push-user-name: # optional, default is 
    #     # If empty the no-reply email of the GitHub Actions bot will be used (i.e. `github-actions[bot]@users.noreply.github.com`)
    #     git-push-user-email: # optional, default is 
    #     # Commit message
    #     git-commit-message: # optional, default is terraform-docs: automated action
    #     # If true it will sign-off commit
    #     git-push-sign-off: # optional, default is false
    #     # Fail the job if there is any diff found between the generated output and existing file (ignored if `git-push` is set)
    #     fail-on-diff: # optional, default is false
          





















  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.destroy != 'true' }}

    env:
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
    - name: Azure CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Cache Terraform state and dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.TF_WORKING_DIR }}/.terraform
          ${{ env.TF_WORKING_DIR }}/.terraform.lock.hcl
          ${{ env.TF_WORKING_DIR }}/tfplan
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf*') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Format
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform fmt -check

    - name: Terraform Plan
      id: tf-plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        if [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
        else 
          exit 0
        fi

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ${{ env.TF_WORKING_DIR }}/tfplan

    - name: Create String Output
      id: tf-plan-string
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo '```terraform' >> $GITHUB_OUTPUT
        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "</details>" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Publish Terraform Plan to Task Summary
      env:
        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
      run: echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

    - name: Push Terraform Output to PR
      if: github.ref != 'refs/heads/main'
      uses: actions/github-script@v7
      env:
        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const body = `${process.env.SUMMARY}`;
          github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
          })

  terraform-apply:
    name: 'Terraform Apply'
    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
    runs-on: ubuntu-latest
    needs: [terraform-plan]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Cache Terraform state and dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.TF_WORKING_DIR }}/.terraform
          ${{ env.TF_WORKING_DIR }}/.terraform.lock.hcl
          ${{ env.TF_WORKING_DIR }}/tfplan
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf*') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -auto-approve tfplan

  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: []

    if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'

    steps:
    - name: Azure CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Destroy
      id: destroy
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform destroy -no-color --auto-approve
